### ISSUE TITLE
Tests fail to compile with mpfr 4.2.0

### ISSUE THREAD

**Issue by musicinmybrain** [shibatch/sleef#470]
Since mpfr 4.2.0 ([changelog link](https://gitlab.inria.fr/mpfr/mpfr/-/blob/4.2.0/ChangeLog)), the tests fail to compile:

```
In file included from /builddir/build/BUILD/sleef-3.5.1/src/libm-tester/tester2simddp.c:23:
/builddir/build/BUILD/sleef-3.5.1/src/libm-tester/testerutil.h:93:6: error: conflicting types for ‘mpfr_sinpi’; have ‘
void(__mpfr_struct *, __mpfr_struct *, mpfr_rnd_t)’
   93 | void mpfr_sinpi(mpfr_t ret, mpfr_t arg, mpfr_rnd_t rnd);
      |      ^~~~~~~~~~
In file included from /builddir/build/BUILD/sleef-3.5.1/src/libm-tester/tester2simddp.c:9:
/usr/include/mpfr.h:752:21: note: previous declaration of ‘mpfr_sinpi’ with type ‘int(__mpfr_struct *, const __mpfr_st
ruct *, mpfr_rnd_t)’
  752 | __MPFR_DECLSPEC int mpfr_sinpi (mpfr_ptr, mpfr_srcptr, mpfr_rnd_t);
      |                     ^~~~~~~~~~
/builddir/build/BUILD/sleef-3.5.1/src/libm-tester/testerutil.h:94:6: error: conflicting types for ‘mpfr_cospi’; have ‘
void(__mpfr_struct *, __mpfr_struct *, mpfr_rnd_t)’
   94 | void mpfr_cospi(mpfr_t ret, mpfr_t arg, mpfr_rnd_t rnd);
      |      ^~~~~~~~~~
/usr/include/mpfr.h:753:21: note: previous declaration of ‘mpfr_cospi’ with type ‘int(__mpfr_struct *, const __mpfr_st
ruct *, mpfr_rnd_t)’
  753 | __MPFR_DECLSPEC int mpfr_cospi (mpfr_ptr, mpfr_srcptr, mpfr_rnd_t);
      |                     ^~~~~~~~~~
```

MPFR upstream added `mpfr_sinpi` and `mpfr_cospi` to the API in 4.2.0, and the prototypes conflict with those in `src/libm-tester/testerutil.h`.

I’ll try to work up a PR to fix this by using the upstream versions of these functions when available.

**Comment by musicinmybrain** [comment]
The [NEWS file](https://gitlab.inria.fr/mpfr/mpfr/-/blob/01a3ed526583e7fea7a3460ad9c85bde8fa3a44b/NEWS) is more useful than the `ChangeLog` in this case, I think.

**Comment by musicinmybrain** [comment]
I somehow missed that this is already reported as #458.
