### PR TITLE
Fix gnuabi if not part of the build

### PR DESCRIPTION
**Pull request by xoofx**
This is a small fix to prevent trying to build GNU Abi if it is not enabled. I was getting an error with `TARGET_LIBSLEEFGNUABI` not being defined `line 102`.

### CODE REVIEW

**Comment by shibatch** [comment]
The check by Travis CI is failing. Please click "Details" link in the right side of "The Travis CI build failed" message, and check if you can fix this.

**Comment by xoofx** [comment]
Yeah, I was already happening on the previous PR #65... will check why...

**Comment by xoofx** [comment]
The error is at [line 706](https://travis-ci.org/shibatch/sleef/jobs/279014051#L706) is

```
/home/travis/build/shibatch/sleef/src/arch/helperavx512f.h:131:93: error: use of
      undeclared identifier '_MM_CMPINT_EQ'
  ...x, vmask y) { return _mm512_cmp_epi64_mask(x, y, _MM_CMPINT_EQ); }
```

I haven't touch anything related to this and the previous #64 was also failing... but reverting #64 via #65 doesn't help... so there is something wrong elsewhere...

**Comment by xoofx** [comment]
Closing this branch. Going to reopen a new branch with all the fixes for Windows MSVC
