### ISSUE TITLE
Issue when compile with gcc 5.5

### ISSUE THREAD

**Issue by nandra** [shibatch/sleef#435]
Hello, I'm trying to add sleef-native support to yocto and hitting following issue:
```
[ 62%] Building C object src/libm/CMakeFiles/sleefavx512fnofma.dir/sleefsimddp.c.o
cd /home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/.build/src/libm && /home/marek/projects/kas-test/build/tmp/hosttools/gcc -DDORENAME=1 -DENABLE_ALIAS=1 -DENABLE_AVX512FNOFMA=1 -DENABLE_BUILTIN_MATH=1 -DENABLE_SYS_getrandom=1 -DSLEEF_STATIC_LIBS=1 -I/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/common -I/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/arch -I/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/.build/src/libm/include -I/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/libm  -Wall -Wno-unused -Wno-attributes -Wno-unused-result -Wno-psabi -ffp-contract=off -fno-math-errno -fno-trapping-math -DNDEBUG   -mavx512f -std=gnu99 -o CMakeFiles/sleefavx512fnofma.dir/sleefsimddp.c.o   -c /home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/libm/sleefsimddp.c

/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/libm/sleefsimddp.c: In function ‘Sleef_sind8_u35avx512fnofma’:
/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/libm/sleefsimddp.c:535:1: error: unrecognizable insn:
 }
 ^
(insn 138 137 139 20 (set (mem/c:V4DF (plus:DI (reg/f:DI 82 virtual-stack-vars)
                (const_int -76704 [0xfffffffffffed460])) [0 hi+0 S32 A256])
        (vec_merge:V4DF (vec_select:V4DF (reg:V8DF 933)
                (parallel [
                        (const_int 4 [0x4])
                        (const_int 5 [0x5])
                        (const_int 6 [0x6])
                        (const_int 7 [0x7])
                    ]))
            (reg:V4DF 934)
            (reg:QI 935))) /home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/arch/helperavx512f.h:146 -1
     (nil))
/home/marek/projects/kas-test/build/tmp/work/x86_64-linux/sleef-native/3.4.1-r0/git/src/libm/sleefsimddp.c:535:1: internal compiler error: in extract_insn, at recog.c:2343
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/libm/CMakeFiles/sleefavx512fnofma.dir/build.make:80: recipe for target 'src/libm/CMakeFiles/sleefavx512fnofma.dir/sleefsimddp.c.o' failed
```
Any idea what should I check? Thanks.

**Comment by nandra** [comment]
ok with clang it works fine. Closing.
